const UserRouter = require('./UserRouter')
const ProductRouter = require('./ProductRouter')
const OrderRouter = require('./OrderRouter')
const CartRouter = require('./CartRouter')
const CouponRouter = require('./CouponRouter')
const PaymentRouter = require('./PaymentRouter')
const RatingRouter = require('./RatingRouter')
const CodeRouter = require('./CodeRouter')

const adminCouponRouter = require('./adminCouponRouter')
const adminUserRouter = require('./adminUserRouter')
const adminProductRouter = require('./adminProductRouter')
const adminLoginRouter = require('./adminLoginRouter')
const adminOrderRouter = require('./adminOrderRouter')
const adminPaymentRouter = require('./adminPaymentRouter')
const routes = (app) => {
    app.use('/api/user', UserRouter)
    app.use('/api/product', ProductRouter)
    app.use('/api/order', OrderRouter)
    app.use('/api/cart', CartRouter) 
    app.use('/api/coupon', CouponRouter) 
    app.use('/api/payment', PaymentRouter)
    app.use('/api/rating', RatingRouter)
    app.use('/api/forgot-pass', CodeRouter)
    app.use('/api/auth-email', CodeRouter)

    app.use('/admin/user', adminUserRouter)
    app.use('/admin/product', adminProductRouter)
    app.use('/admin/coupon', adminCouponRouter)
    app.use('/admin/order', adminOrderRouter) 
    app.use('/admin/payment', adminPaymentRouter)
    app.use('/admin/',adminLoginRouter)
}

module.exports = routes